---
# handlers file for roles/network

- name: restart iptables
  systemd:
    name: iptables
    state: restarted

- name: restart network
  systemd:
    name: network
    state: restarted
    
- name: restart sshd
  systemd:
    name: sshd
    state: restarted
